### ISSUE TITLE
Coding of `Month`.

### ISSUE THREAD

**Issue by YOCKOW** [koher/swift-ymd#1]
https://github.com/koher/swift-ymd/blob/8ba34c4e250885dddae2b33a60077526ad629ba8/Sources/SwiftYMD/Month.swift#L22-L36

Out of mere curiosity...
Why don't you use integer values for de/encoding?
* `guard let month = Month.allCases...` -> `guard let month = Month(rawValue: try container.decode(Int.self))`
* `try container.encode(description)` -> `try container.encode(self.rawValue)`

Aren't there any problems about processing speed?

**Comment by koher** [comment]
I chose it because, for example, `"December"` in JSONs is more obvious to mean December than `12` is.

**Comment by YOCKOW** [comment]
Thank you for the response.
Now I understand the reason.
